name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Typecheck
        run: npx tsc --noEmit -p backend/tsconfig.json

      - name: Run Tests
        run: npm run test:backend

      - name: Build App
        run: npm run build:backend

  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Typecheck
        run: npx tsc --noEmit -p frontend/tsconfig.json

      - name: Run Tests
        run: npm run test:frontend

      - name: Build App
        run: npm run build:frontend
